version: '3'
services:
  flask-app:
    build: .
    restart: always
    volumes:
      - .:/app
    command: gunicorn -b 0.0.0.0:5000 main:app
    depends_on:
      - redis-server
  redis-server:
    image: redis
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app
