version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/app
    command: gunicorn -b 0.0.0.0:5000 main:app
  redis-server:
    image: redis